global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'event-orchestrator'

    static_configs:
      - targets: ['app:3000']
        labels:
          environment: 'development'
